Repository aws/aws-sdk-php, pull requests merged in 2018-05, with the labels that each got.

#1541 Status Code Checking in Smoke/Integ Tests
  .changes/nextrelease/update_ecs_smoke_test.json
  features/smoke/ecs.feature
  tests/Integ/SmokeContext.php
Labels: Ready-for-review

#1542 Add Changelog Document Verification Tests
  .changes/nextrelease/changelog_document_tests.json
  tests/Build/Changelog/CurrentChangesTest.php
Labels: Ready-for-review

#1519 use namespaced phpunit
  tests/S3/Crypto/S3EncryptionMultipartUploaderTest.php
Labels: Ready-for-review, awaiting-reply, enhancement

#1543 S3Context Validation Fix
  tests/Integ/S3Context.php
Labels: Ready-for-review

#1545 Updating urls to new location for v3 developer guide.
  README.md
Labels: PR-under-review, docs

#1555 Add smoke test for SecretsManager.
  features/smoke/secretsmanager.feature
Labels: Ready-for-review

#1554 Disable ECS Credentials Lookup Proxies
  .changes/nextrelease/override_ecs_proxy.json
  src/Credentials/EcsCredentialProvider.php
  tests/Credentials/EcsCredentialProviderTest.php
Labels: Ready-for-review

#1558 S3 Addressing Compliance Tests
  .changes/nextrelease/s3_addressing_tests.json
  tests/S3/S3EndpointMiddlewareTest.php
  tests/S3/test_cases/uri_addressing.json
Labels: Ready-for-review

#1559 Add GDPR banner.
  build/docs/theme/@layout.latte
  docs/_templates/layout.html
Labels: Ready-for-review
