Repository aws/aws-sdk-php, pull requests merged in 2018-08, with the labels that each got.

#1597 Sort 'Service APIs' by namespace
  build/docs/classes/DocsBuilder.php
Labels: Ready-for-review, docs

#1604 compatible to namespaced phpunit classes
  .changes/nextrelease/namespaced_phpunit_classes.json
  tests/ClientResolverTest.php
  tests/DynamoDb/StandardSessionConnectionTest.php
  tests/S3/StreamWrapperPathStyleTest.php
  tests/S3/StreamWrapperTest.php
  tests/S3/TransferTest.php
  tests/bootstrap.php
Labels: PR-under-review, enhancement

#1610 `'X-Amz-Security-Token'` Presign Fix
  .changes/nextrelease/security_token_header_fix.json
  src/Signature/SignatureV4.php
  tests/Signature/SignatureV4Test.php
Labels: PR-under-review, bug

#1607 Add ini parse directive
  .changes/nextrelease/ini_scanner_raw_update.json
  src/Credentials/CredentialProvider.php
  tests/Credentials/CredentialProviderTest.php
Labels: Ready-for-review, enhancement
