Repository aws/aws-sdk-php, pull requests merged in 2018-02, with the labels that each got.

#1497 S3\Transfer::construct(): correct docs
  src/S3/Transfer.php
Labels: docs

#1487 Removed useless else after return
  src/Api/Serializer/RestSerializer.php
  src/Api/Service.php
  src/ClientResolver.php
  src/Crypto/EncryptionTrait.php
  src/DynamoDb/Marshaler.php
  src/HandlerList.php
  src/History.php
  src/IdempotencyTokenMiddleware.php
  src/Multipart/AbstractUploadManager.php
  src/RetryMiddleware.php
  src/S3/Crypto/CryptoParamsTrait.php
  src/S3/S3Client.php
  src/S3/S3EndpointMiddleware.php
  src/Sdk.php
  src/TraceMiddleware.php
  src/Waiter.php
  src/functions.php
Labels: PR-under-review, awaiting-reply, enhancement

#1502 Signer Unquoted Integers Fix
  .changes/nextrelease/signer_int_fix.json
  src/CloudFront/Signer.php
  tests/CloudFront/SignerTest.php
  tests/CloudFront/UrlSignerTest.php
Labels: Ready-for-review, bug
